### ISSUE TITLE
Button doesn't define onClick handler

### ISSUE THREAD

**Issue by nabati** [Adrinlol/landy-react-template#10]
For instance, MiddleBlock is instansiating <Button /> component and with an onClick prop, but the Button component itself is not doing anything with the onClick prop.

**Comment by Adrinlol** [comment]
My bad! 

Totally forgot about that issue.

Thank you for pointing out the root of this bug.

**Comment by nabati** [comment]
np. thanks for the template, saved me a lot of time. :)

**Comment by Adrinlol** [comment]
Glad you liked it!
