### ISSUE TITLE
Installation failure on v1.3.6

### ISSUE THREAD

**Issue by yakkomajuri** [Adrinlol/landy-react-template#19]
Hey, awesome project!

Installation for me failed on the latest version (v1.3.6). Using v1.3.4 worked.

Here's the error:

```shell
SyntaxError: /Local/Path/node_modules/cra-template-adrinlol/template.json: Unexpected token } in JSON at position 564
    at parse (<anonymous>)
```

I have Node v16 btw.

**Comment by yakkomajuri** [comment]
Looked into this - was a tiny thing: an extra comma in `template.json` #20

**Comment by subbuballa** [comment]
> Looked into this - was a tiny thing: an extra comma in `template.json` #20

I got the same error, thanks for the tip, using lower version worked for me

**Comment by Adrinlol** [comment]
@yakkomajuri Really appreciate you taking the time to look into and fix the problem.

Thanks a lot!
