### ISSUE TITLE
Missing react-router-dom

### ISSUE THREAD

**Issue by mguldner** [Adrinlol/landy-react-template#22]
Hi,

I just created a project with your template, seems awesome, excited to explore it! :)

Just to point out that, at first run after install following your instructions on Readme, the `package.json` is missing 'react-router-dom' called in `index.tsx`.

I just `npm i react-router-dom` to correct it.

Thanks for your project :)

**Comment by Adrinlol** [comment]
Hey @mguldner,

Glad you like the project!

Thank you for reporting the issue, I will fix it right away.
