### ISSUE TITLE
Request Footer stick to bottom

### ISSUE THREAD

**Issue by Zanoshky** [Adrinlol/landy-react-template#30]
Hey, 

I would like to request if you can make a footer stick to the bottom of the page via a param?

`<Footer  stickBottom/>`

Some pages, do not have lots of content and would be visually appealing.

**Comment by buddywhitman** [comment]
hey y'all i am working on tis.. lookingup the MUI and chakra UI libraries for a component matching these specs.. feel free to suggest other libraries
