### ISSUE TITLE
Project not working!

### ISSUE THREAD

**Issue by salimdellali** [Adrinlol/landy-react-template#33]
I downloaded the project, executed `npm install` and got errors, spent hours trying to manually fix but every time I fix something, another error pops up , please review the project

**Comment by Adrinlol** [comment]
@salimdellali did you create the project using npx? https://github.com/Adrinlol/landy-react-template#installation

**Comment by salimdellali** [comment]
Indeed, I tried using `npx` and it worked!

I have 2 suggestions in order to help people not face some of problems I got: 

1. in `README.MD` better to move the `Installation` part upper in the document, because it's in the middle of other parts and can easily be skipped while skimming the headlines.
2. while searching for react templates, I came across this website [https://morioh.com/p/d4b77942bd24](https://morioh.com/p/d4b77942bd24), this is how I found your template, but unfortunately the `live demo` link is not working properly. If you own this blog post, please update the `live demo` link
