### ISSUE TITLE
Language switch doesn't work

### ISSUE THREAD

**Issue by mostafachatillon** [Adrinlol/landy-react-template#4]
Hi, the language switch only translates the contact info, not the whole page

**Comment by Adrinlol** [comment]
Hi mostafachatillon,

The language switch button only translates the texts in header & footer, other content isn't included in the translation, you have to add the content yourself, that's the whole idea behind this template.

**Comment by mostafachatillon** [comment]
I don't get the whole idea. The template said : "Save weeks of time and
build your landing page in minutes.", but it will be very time consuming to
finish the work (for someone who doesn't know how the code is structured)
