### ISSUE TITLE
How do i replace the images seems like you have use svg files/icon.

### ISSUE THREAD

**Issue by ayush431** [Adrinlol/landy-react-template#48]

**Comment by sabeerbikba** [comment]
It seems there was some confusion regarding the use of images, specifically SVG files or icons. I'd like to clarify that this project supports the use of any type of image, not just SVGs. To use images, you need to place them in the **public/img/svg** folder. This is not limited to SVG files; you can use any image format supported by web browsers, such as PNG, JPEG, or GIF.

### Here's how you can replace images in this project:

- **For General Content Blocks:** If you're using a **ContentBlock** component and want to replace the **icon**, you can simply change the icon prop to the name of your new image file. Make sure the image is placed in the **public/img/svg** folder.

```javascript
<ContentBlock
  direction="right"
  title={IntroContent.title}
  content={IntroContent.text}
  button={IntroContent.button}
  icon="new-image.png" // Replace "new-image.png" with your image file name
  id="intro"
/>
```

- **For SVG Icons:** If you're using an **SvgIcon** component and want to replace the icon, you can change the **src** prop to the path of your new image file. Again, ensure the image is placed in the **public/img/svg** folder.

```javascript
<SvgIcon src="new-image.png" width="20px" height="20px" /> // Replace "new-image.png" with your image file name
```

By following these steps, you can easily replace images in our project with any type of image file. Just make sure to update the file name in the code to match the name of your new image file.

**Comment by Adrinlol** [comment]
@sabeerbikba, just wanted to drop a quick thank you for the helpful step-by-step instructions on changing the images! Much appreciated!
