### ISSUE TITLE
any plan for typescript migration?

### ISSUE THREAD

**Issue by sickyoon** [Adrinlol/landy-react-template#7]
awesome template! any plans for typescript migration?

**Comment by Adrinlol** [comment]
Hi sickyoon,

I'm glad you liked this template. 

As this project is fairly small and most of the beginner Frontend Developers don't know TypeScript, I decided to stick with JS.

But I plan create an improved template using TypeScript with additional sections/pages (pricing, payment with stripe, leaflet, about us, etc..) in the near future.

**Comment by nabati** [comment]
I guess it doesn't really matter for a single-use landing page. My $0.02.
